api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

contacto_id:
    path: '/prueba'
    defaults:
        _controller: 'AppBundle:Contact:getById'

#contacto_special:
#    path: '/contacto/{id}/special'
#    methods:  ['PUT']
#    defaults:
#        _controller: 'AppBundle:Contact:special'
#        _api_resource_class: 'AppBundle\Entity\Contact'
#        _api_item_operation_name: 'special'