api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

contacto_id:
    path: '/prueba'
    defaults:
        _controller: 'AppBundle:Contact:getById'
