api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

encuesta_add:
    path: '/encuesta/add'
    defaults:
        _controller: 'AppBundle:Encuesta:add'

encuesta_get:
    path: '/encuesta/get/{id}'
    defaults:
        _controller: 'AppBundle:Encuesta:get'
    requirements:
        page: '\d+'

encuestas_contacto:
    path: '/encuestas/contacto/get/{id}'
    defaults:
        _controller: 'AppBundle:Encuesta:getEncuestasByContacto'
    requirements:
        page: '\d+'